#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd "$DIR"
docker build --pull -t gcr.io/surveyadmin-001/pt-log .
docker push gcr.io/surveyadmin-001/pt-log
